/**
 * Datasets for the PCA lab.
 *
 * Both are generated from a known factor structure, which is the entire point:
 * PCA is supposed to RECOVER structure it was not told about, and the only way
 * to check that it does is to build data whose structure you already know.
 */

import { mulberry32, normalSampler } from "@/lib/math/random";
import { nelsonSiegel } from "@/lib/finance/fixedIncome";
import { ASSET_BETAS, CURVE_TENORS } from "@/lib/labs/pca";

/**
 * Asset returns driven by one common factor plus idiosyncratic noise:
 *
 *   r_i = beta_i * F + eps_i
 *
 * This is the single-factor model underneath CAPM. PCA on the resulting
 * covariance should recover a first component whose loadings line up with the
 * betas — without ever being told the betas exist.
 */
export function generateAssetReturns(
  observations: number,
  seed: number,
  marketStrength: number,
  noise: number,
): number[][] {
  const normal = normalSampler(mulberry32(seed));
  const data: number[][] = [];
  for (let t = 0; t < observations; t++) {
    const factor = normal() * marketStrength;
    data.push(ASSET_BETAS.map((beta) => beta * factor + noise * normal()));
  }
  return data;
}

/**
 * Daily changes in a yield curve, generated by shocking the three Nelson-Siegel
 * parameters independently.
 *
 * The parameters have known meanings — level, slope and curvature — so this
 * dataset has exactly three underlying drivers by construction, plus a little
 * measurement noise. If PCA is working, it should find three components that
 * reproduce those shapes, and they should explain almost all the variation.
 *
 * That this result also holds on REAL yield curves, where nobody imposed a
 * Nelson-Siegel structure, is one of the most robust empirical findings in
 * fixed income.
 */
export function generateCurveChanges(
  observations: number,
  seed: number,
  noise: number,
): number[][] {
  const normal = normalSampler(mulberry32(seed));
  const baseLevel = 0.04;
  const baseSlope = -0.015;
  const baseCurvature = 0.01;

  const data: number[][] = [];
  let previous = CURVE_TENORS.map((t) => nelsonSiegel(t, baseLevel, baseSlope, baseCurvature));

  for (let d = 0; d < observations; d++) {
    // Independent daily shocks to each parameter. Level moves most, curvature
    // least — which mirrors what is observed in practice.
    const level = baseLevel + 0.0045 * normal();
    const slope = baseSlope + 0.0030 * normal();
    const curvature = baseCurvature + 0.0018 * normal();

    const curve = CURVE_TENORS.map(
      (t) => nelsonSiegel(t, level, slope, curvature) + noise * 0.0002 * normal(),
    );
    // PCA is run on CHANGES, not levels. Rate levels are non-stationary — they
    // wander — so a PCA of levels would mostly recover "rates were higher in the
    // first half of the sample", which is not a factor structure.
    data.push(curve.map((rate, i) => rate - previous[i]));
    previous = curve;
  }
  return data;
}
