export interface GlossaryEntry {
  term: string;
  category: "Statistics" | "Portfolio" | "Risk" | "Simulation" | "Strategy" | "Derivatives" | "Machine learning";
  definition: string;
  note?: string;
  related?: string[];
  lessonSlug?: string;
}

export const GLOSSARY: GlossaryEntry[] = [
  { term: "Alpha", category: "Portfolio", definition: "Return not explained by exposure to a benchmark. Formally, the intercept in a regression of a portfolio's returns on the benchmark's returns.", note: "Alpha is defined relative to a specific benchmark. Change the benchmark and the alpha changes, which is why 'alpha' claims require stating what was controlled for.", related: ["Beta"] },
  { term: "Beta", category: "Portfolio", definition: "Sensitivity of an asset's returns to a benchmark's returns. Covariance with the benchmark divided by the benchmark's variance.", note: "Beta of 1 means the asset moves with the market on average; 1.5 means it tends to move 50% more.", lessonSlug: "linear-regression", related: ["Alpha", "Covariance"] },
  { term: "Sharpe ratio", category: "Risk", definition: "Excess return over the risk-free rate divided by the standard deviation of returns.", note: "Its standard error is roughly √((1+S²/2)/n). A one-year Sharpe of 1.0 has a standard error near 1.2, so it is statistically indistinguishable from zero.", lessonSlug: "sharpe-ratio", related: ["Sortino ratio", "Volatility"] },
  { term: "Sortino ratio", category: "Risk", definition: "Excess return divided by downside deviation rather than total volatility.", note: "Stops penalising a strategy for upside volatility. Exceeds the Sharpe ratio when returns are positively skewed.", related: ["Sharpe ratio"] },
  { term: "Volatility", category: "Risk", definition: "The annualised standard deviation of returns.", note: "Scales with the square root of time, because variances add for independent returns while standard deviations do not.", lessonSlug: "variance-and-standard-deviation" },
  { term: "Drawdown", category: "Risk", definition: "The percentage decline from a portfolio's running maximum to a subsequent low.", note: "Path-dependent: reordering the same set of returns changes it. This is what makes it capture something volatility cannot.", lessonSlug: "drawdown" },
  { term: "Correlation", category: "Statistics", definition: "Covariance divided by the product of both standard deviations, giving a dimensionless value in [−1, 1].", note: "Measures linear association only. Two variables can be perfectly dependent and have zero correlation.", lessonSlug: "correlation", related: ["Covariance"] },
  { term: "Covariance", category: "Statistics", definition: "The expected product of two variables' deviations from their means.", note: "Its units are the product of both variables' units, which is why correlation — the normalised version — is usually more useful.", lessonSlug: "covariance" },
  { term: "Expected value", category: "Statistics", definition: "The probability-weighted average of all possible outcomes.", note: "Need not be an achievable outcome. The expected value of a die roll is 3.5.", lessonSlug: "expected-value" },
  { term: "Variance", category: "Statistics", definition: "The expected squared deviation from the mean.", note: "Can never be negative. For a sample, divide by n−1 rather than n — Bessel's correction.", lessonSlug: "variance-and-standard-deviation" },
  { term: "Standard deviation", category: "Statistics", definition: "The square root of variance, restoring the original units.", lessonSlug: "variance-and-standard-deviation" },
  { term: "Skewness", category: "Statistics", definition: "A measure of a distribution's asymmetry. Negative means a longer left tail.", note: "Equity returns are typically negatively skewed: many small gains, occasional large losses." },
  { term: "Kurtosis", category: "Statistics", definition: "A measure of how much variance comes from rare extreme values. 'Excess' kurtosis subtracts 3 so a normal distribution scores zero.", note: "Positive excess kurtosis means fat tails — extreme moves are more likely than a normal distribution predicts." },
  { term: "Monte Carlo simulation", category: "Simulation", definition: "Estimating a quantity by generating many random samples and averaging them.", note: "Error shrinks as 1/√N, so halving it requires four times the samples.", lessonSlug: "monte-carlo-simulation" },
  { term: "Random walk", category: "Simulation", definition: "A process whose next value is the current value plus an independent random step.", note: "The null hypothesis for market predictability. Random walks produce convincing-looking trends and patterns that mean nothing.", lessonSlug: "random-walks" },
  { term: "Geometric Brownian motion", category: "Simulation", definition: "A continuous-time process in which proportional changes follow a random walk, making the level log-normally distributed.", note: "The −σ²/2 term in its solution is the Itô correction, without which volatility would manufacture free expected growth.", lessonSlug: "geometric-brownian-motion", related: ["Random walk"] },
  { term: "Markov process", category: "Simulation", definition: "A process in which the next state depends only on the current state, not on the path taken to reach it.", note: "Expected run length in a state is 1/(1 − P(stay)), which is what determines whether a hidden state is detectable at all.", lessonSlug: "markov-chains" },
  { term: "Market regime", category: "Simulation", definition: "A persistent period during which market behaviour — drift, volatility, correlation — is statistically distinct.", note: "Mixing normal distributions with different variances produces fat tails and volatility clustering from entirely Gaussian parts.", lessonSlug: "market-regimes" },
  { term: "Backtesting", category: "Strategy", definition: "Simulating how a trading rule would have performed on historical or synthetic data.", note: "Only as honest as its treatment of information. The position must be decided using data available before the return it earns.", lessonSlug: "backtesting" },
  { term: "Overfitting", category: "Machine learning", definition: "Fitting the noise in a particular sample rather than the structure of the underlying process.", note: "Selecting the best of n noisy estimates inflates the result by roughly √(2 ln n) standard errors, even when nothing is there.", lessonSlug: "overfitting" },
  { term: "Look-ahead bias", category: "Strategy", definition: "Using information in a backtest that would not have been available at the time of the decision.", note: "The most common and most damaging backtesting error, because it fails silently — the equity curve simply rises.", lessonSlug: "backtesting" },
  { term: "Survivorship bias", category: "Strategy", definition: "Testing only on assets that still exist today, excluding those that failed or were delisted.", note: "Systematically inflates historical returns, because the failures are precisely what is missing." },
  { term: "Slippage", category: "Strategy", definition: "The difference between the price assumed when a trade is decided and the price actually achieved.", related: ["Transaction cost"] },
  { term: "Transaction cost", category: "Strategy", definition: "The total cost of trading: commissions, bid-ask spread, market impact, slippage and taxes.", note: "Scales with turnover. For a high-turnover rule it is the dominant term, not a correction.", lessonSlug: "transaction-costs" },
  { term: "Liquidity", category: "Strategy", definition: "How easily an asset can be traded in size without moving its price.", note: "Tends to disappear exactly when it is most needed, which is why liquidity risk is not well captured by volatility." },
  { term: "Turnover", category: "Strategy", definition: "The total absolute change in position over a period, as a multiple of portfolio value.", note: "The single number that determines how much transaction costs will matter." },
  { term: "Value at Risk", category: "Risk", definition: "A loss threshold exceeded only (1 − c) of the time, for confidence level c.", note: "NOT the worst possible loss. It says nothing about how much worse than the threshold things can get, and it is not subadditive.", related: ["Conditional Value at Risk"] },
  { term: "Conditional Value at Risk", category: "Risk", definition: "The average loss given that the Value at Risk threshold has been breached. Also called expected shortfall.", note: "Always at least as large as VaR, and coherent — unlike VaR, it can never make diversification appear to increase risk.", related: ["Value at Risk"] },
  { term: "Distribution shift", category: "Machine learning", definition: "When deployment data comes from a different distribution than training data.", note: "Distinct from overfitting: the model may have learned correctly, about a world that no longer exists.", lessonSlug: "distribution-shift" },
  { term: "Reinforcement learning", category: "Machine learning", definition: "Learning a policy mapping states to actions through interaction with an environment and reward feedback.", lessonSlug: "reinforcement-learning", related: ["Policy", "Reward function", "State", "Action"] },
  { term: "Reward function", category: "Machine learning", definition: "The scalar signal an RL agent maximises.", note: "The hardest part of applying RL. The agent optimises exactly what you specify, which is rarely exactly what you meant." },
  { term: "State", category: "Machine learning", definition: "The information an agent observes before choosing an action.", note: "Must contain everything decision-relevant, or the problem becomes partially observable and the Markov property fails." },
  { term: "Action", category: "Machine learning", definition: "A choice available to an agent at a given state." },
  { term: "Policy", category: "Machine learning", definition: "A mapping from states to actions, possibly probabilistic. The thing an RL agent learns." },
  { term: "Efficient frontier", category: "Portfolio", definition: "The set of portfolios offering the highest expected return for each level of risk.", note: "Its curvature IS the diversification benefit. A straight frontier would mean correlation of exactly +1.", lessonSlug: "portfolio-theory" },
  { term: "Diversification", category: "Portfolio", definition: "Reducing portfolio risk by combining imperfectly correlated assets.", note: "Arises because expected return is linear in the weights while risk is quadratic. The cross term carries the correlation.", lessonSlug: "correlation" },
  { term: "Options", category: "Derivatives", definition: "Contracts giving the right, but not the obligation, to buy (call) or sell (put) an asset at a fixed strike price.", related: ["Delta", "Gamma", "Theta", "Vega"] },
  { term: "Delta", category: "Derivatives", definition: "Change in an option's value per $1 change in the underlying. Also the hedge ratio.", note: "Equals N(d₁) for a call, which is a probability under the stock-numeraire measure — not the probability of expiring in the money." },
  { term: "Gamma", category: "Derivatives", definition: "The rate at which delta changes as the underlying moves.", note: "Identical for calls and puts, which follows directly from put-call parity. Peaks at the money." },
  { term: "Theta", category: "Derivatives", definition: "Value lost per day from the passage of time alone.", note: "Normally negative for a long option, and most negative at the money near expiry." },
  { term: "Vega", category: "Derivatives", definition: "Change in option value per one percentage point change in volatility.", note: "Not a Greek letter. Identical for calls and puts." },
  { term: "Rho", category: "Derivatives", definition: "Sensitivity of an option's value to the risk-free interest rate.", note: "Usually the least important Greek, except for long-dated options." },
  { term: "Implied volatility", category: "Derivatives", definition: "The volatility that makes the Black-Scholes price equal the observed market price.", note: "That it varies with strike and expiry — the volatility smile — is direct market evidence that the model's constant-volatility assumption is false." },
  { term: "Risk-neutral measure", category: "Derivatives", definition: "A probability measure under which discounted asset prices are martingales, so a derivative's price is its discounted expected payoff.", note: "Not an assumption that investors are indifferent to risk. It is a change of measure justified by the ability to replicate the payoff." },
  { term: "Law of large numbers", category: "Statistics", definition: "The sample mean converges to the true expected value as the sample grows.", note: "Says nothing about the rate, and nothing about individual outcomes. Misreading it produces the gambler's fallacy.", lessonSlug: "law-of-large-numbers" },
  { term: "Central limit theorem", category: "Statistics", definition: "The standardised sample mean converges to a normal distribution regardless of the original distribution's shape.", note: "Requires independence and finite variance — exactly the conditions markets violate.", lessonSlug: "central-limit-theorem" },
  { term: "Autocorrelation", category: "Statistics", definition: "The correlation of a series with a time-shifted copy of itself.", note: "The autocorrelation of SQUARED returns is usually strongly positive even when returns themselves show none. That is volatility clustering.", lessonSlug: "autocorrelation" },
  { term: "Stationarity", category: "Statistics", definition: "A series is stationary if its statistical properties do not depend on when you observe it.", note: "Prices are not stationary; returns approximately are. Nearly every statistical tool assumes it.", lessonSlug: "stationarity" },
];

export const GLOSSARY_CATEGORIES = [
  "Statistics", "Simulation", "Portfolio", "Risk", "Strategy", "Derivatives", "Machine learning",
] as const;
