export interface JournalPost {
  slug: string;
  title: string;
  date: string;
  summary: string;
  readingMinutes: number;
  sections: { heading: string; paragraphs: string[]; equation?: string; equationNote?: string }[];
  references?: string[];
}

export const JOURNAL_POSTS: JournalPost[] = [
  {
    slug: "why-backtests-lie",
    title: "Why backtests lie",
    date: "2026-09-30",
    summary:
      "A backtest on a market with provably zero signal produced an in-sample Sharpe of 0.557 and an out-of-sample Sharpe of −0.890. Here is the mechanism, and why it is not a bug.",
    readingMinutes: 7,
    sections: [
      {
        heading: "The experiment",
        paragraphs: [
          "I built a market with an AR(1) coefficient of exactly zero. Returns are independent by construction, so no rule based on past prices can have any expected edge whatsoever. This is not an assumption about the market — it is a property of the code that generated it.",
          "I then searched a grid of moving-average crossover parameters, picked the one with the highest Sharpe ratio on the first half of the data, and evaluated it on the final quarter, which the search never saw.",
          "In-sample Sharpe: 0.557. Out-of-sample Sharpe: −0.890. The correlation between in-sample and out-of-sample Sharpe across the entire grid was −0.005.",
        ],
      },
      {
        heading: "Why this happens",
        paragraphs: [
          "Each parameter combination's in-sample Sharpe is a noisy estimate of its true Sharpe, which here is exactly zero for every combination. The estimates scatter around zero with a standard error that depends on the sample length.",
          "Taking the maximum of many such estimates does not find the best strategy. There is no best strategy — they are all identical in truth. It finds the estimate with the largest positive error.",
          "The expected maximum of n independent standard normal draws grows roughly like the square root of 2 ln n. So the inflation gets worse the harder you search, and it never stops growing.",
        ],
        equation: "E\\left[\\max_{1 \\le i \\le n} Z_i\\right] \\approx \\sqrt{2\\ln n}",
        equationNote:
          "This is why 'we tested hundreds of variants and this one worked best' is a warning rather than a reassurance.",
      },
      {
        heading: "The number that convinced me",
        paragraphs: [
          "The correlation of −0.005 between in-sample and out-of-sample Sharpe is the one I keep returning to. It says that knowing a strategy's historical rank tells you literally nothing about its future rank — not a weakened signal, not a noisy signal, nothing.",
          "That is exactly what theory predicts when there is no signal. Seeing the prediction hold in a simulation I wrote myself was more persuasive than reading it would have been, because I knew for certain there was nothing to find.",
        ],
      },
      {
        heading: "What this does not prove",
        paragraphs: [
          "It does not prove that all backtests are worthless, or that no strategy has an edge. It proves that a backtest cannot distinguish between a real edge and a selected accident, unless you know how large the search was — and the size of the search is almost never reported.",
          "The honest defences are the boring ones: hold out data and touch it once, prefer fewer parameters, report how many variants you tried, and test on data generated by a process you control so you know what the right answer is.",
        ],
      },
    ],
  },
  {
    slug: "how-transaction-costs-affect-strategies",
    title: "How transaction costs affect strategies",
    date: "2026-09-30",
    summary:
      "An Oracle strategy that knows the hidden market regime beats buy-and-hold before costs and loses to it after. Perfect information is not enough.",
    readingMinutes: 6,
    sections: [
      {
        heading: "The Oracle",
        paragraphs: [
          "While building the Backtesting Lab I added an Oracle strategy: one that sees the hidden regime directly and holds the market only during bull states. It cannot be run on real data — it uses information that does not exist outside the simulation. Its purpose is to measure whether the environment contains exploitable structure at all.",
          "Before costs, the Oracle achieved a Sharpe of 0.491 against buy-and-hold's 0.447. The structure is genuinely there.",
          "After 0.1% transaction costs — a realistic retail figure — the Oracle scored 0.389 against buy-and-hold's 0.447. It traded 93 times over ten years and gave up 13.4% of total return to do so.",
        ],
      },
      {
        heading: "Why this matters more than it first appears",
        paragraphs: [
          "The Oracle is an upper bound. No regime-timing strategy on that market can do better than one that already knows the answer. If perfect information cannot beat doing nothing after costs, no amount of cleverness in regime detection will either.",
          "Any real strategy faces strictly worse conditions: it must estimate the state from noisy data, it will be late, it will be wrong sometimes, and it pays the same costs. The Oracle result establishes that the problem was unprofitable before any of those difficulties were added.",
        ],
      },
      {
        heading: "Cost scales with turnover, which is a property of the rule",
        paragraphs: [
          "This is the part that is easy to state and easy to forget. Transaction cost is not a small correction applied at the end. For a high-turnover rule it is the dominant term.",
          "A strategy turning over 50 times a year at 0.1% per trade must earn 5% annually before producing anything at all. Buy-and-hold pays that cost once, not fifty times, which is why it is such a demanding benchmark — it wins partly by not playing.",
        ],
        equation: "\\text{Cost} = c\\sum_t \\left|w_t - w_{t-1}\\right| = c \\times \\text{Turnover}",
      },
      {
        heading: "The cost model here is still optimistic",
        paragraphs: [
          "The lab charges a flat proportional fee and assumes you always trade at the mid price in unlimited size. Real costs include a bid-ask spread that widens exactly when you most want to trade, market impact that grows with position size, slippage between decision and execution, and taxes.",
          "So the conclusion — that perfect information loses to doing nothing — is if anything understated.",
        ],
      },
    ],
  },
  {
    slug: "what-makes-a-market-learnable",
    title: "What makes a market learnable?",
    date: "2026-09-30",
    summary:
      "Persistence, not predictability, determines whether a hidden state leaves a detectable trace. And a detector can be genuinely useful while scoring worse than guessing.",
    readingMinutes: 6,
    sections: [
      {
        heading: "Persistence is the whole game",
        paragraphs: [
          "In a Markov-switching market, the diagonal of the transition matrix controls how long each regime lasts. Run length is geometrically distributed, so the expected duration is one over one minus the persistence.",
          "At 0.97 persistence, a regime lasts about 33 days — long enough for a 40-day rolling statistic to partially resolve it. At 0.5 persistence it lasts two days, and no rolling window of any length can track it. The hidden state still exists and still drives returns; it simply leaves no statistical trace.",
          "This reframes the question. 'Is this market predictable?' is less useful than 'does its structure persist long enough to be estimated before it changes?'",
        ],
        equation: "E[\\text{run length}] = \\frac{1}{1 - P_{ii}}",
      },
      {
        heading: "Second moments are estimable; first moments are not",
        paragraphs: [
          "Building the regime detector made this concrete in a way I had not appreciated. The detector distinguishes bear regimes reasonably well, because bear volatility is 34% against bull's 13% — a gap a rolling estimate can resolve from a few weeks of data.",
          "It confuses bull with sideways almost completely, because that distinction is about drift. Separating a 14% drift from a 1% drift at these volatility levels would take years of data, and by then the regime has changed many times.",
          "This is why volatility forecasting is a mature, successful field and return forecasting is not. It is not that one problem attracted better researchers. The signal-to-noise ratios differ by orders of magnitude.",
        ],
      },
      {
        heading: "A result that looked like a failure",
        paragraphs: [
          "The detector scored 41.6% accuracy against a 45.7% baseline from always guessing the most common regime. My first instinct was that it was broken.",
          "It is not. Its recall on bear regimes was 50.7% against a base rate of 23% — more than double chance on the one state anyone cares about identifying. The accuracy figure is lower because the detector trades many correct majority-class guesses for fewer correct minority-class guesses.",
          "A model that never predicted 'bear' at all would score higher accuracy while being useless. This is why classification work reports per-class recall and precision rather than a single accuracy number, and I now understand why rather than just knowing that.",
        ],
      },
    ],
  },
  {
    slug: "what-i-learned-building-a-market-simulator",
    title: "What I learned building a market simulator",
    date: "2026-09-30",
    summary:
      "Three bugs that produced plausible numbers instead of errors, and what each one taught me about where to be suspicious.",
    readingMinutes: 7,
    sections: [
      {
        heading: "Bug one: a test that refuted a true proposition",
        paragraphs: [
          "I wrote a test asserting that parametric VaR understates tail risk on fat-tailed data. It failed — parametric VaR came out 26 times larger than historical.",
          "The implementation was fine. The test data was wrong. I had constructed 1,000 calm observations plus exactly 10 crashes, then measured the 99% quantile. With exactly 1% contamination, the 99% quantile falls precisely at the boundary between the calm bulk and the crashes, so the historical estimate measured the bulk. Meanwhile the crashes inflated the standard deviation and pushed the parametric estimate up.",
          "Rebuilt as a 95/5 mixture, where the contaminating fraction is comfortably larger than the tail probability being measured, the expected relationship appeared immediately. The lesson: when a test fails, the test is a suspect too.",
        ],
      },
      {
        heading: "Bug two: an uncontrolled comparison",
        paragraphs: [
          "The Risk Analyzer offers four return processes so you can compare risk metrics across different tail shapes. For that comparison to mean anything, all four must have the same volatility — otherwise any difference in VaR confounds tail shape with scale.",
          "The regime-switching process realised 27.1% volatility against a 20% target. I had set the two regime volatilities as multiples of the target without accounting for the stationary mixture. Every cross-process comparison in the lab would have been invalid, in a way no individual number would have revealed.",
          "The fix was to derive the stationary occupancy analytically and rescale so the blended variance matches. The jump process needed the same correction. I only caught it because a test asserted the realised volatility, which I had written mostly out of habit.",
        ],
      },
      {
        heading: "Bug three: a do-nothing strategy winning",
        paragraphs: [
          "In the Overfitting Lab, several parameter combinations had moving-average windows longer than the test segment. Those strategies generated no signal, sat in cash, and scored a Sharpe of exactly zero.",
          "Against a field of losing strategies, zero wins. So the 'best strategy on the test set' was one that never traded. The number was plausible, the chart rendered, nothing errored.",
          "The fix was to admit only combinations that actually trade in all three segments. The general lesson is the one I keep relearning: the dangerous bugs are not the ones that crash. They are the ones that return a number you are willing to believe.",
        ],
      },
      {
        heading: "What I would tell myself at the start",
        paragraphs: [
          "Write the test that checks the thing you believe is obviously true. All three of these were caught by assertions I nearly did not bother writing — that a generator hits its target volatility, that a known textbook value comes out right, that every candidate in a comparison is actually comparable.",
          "And prefer synthetic data while learning. Every one of these bugs was detectable only because I knew the correct answer in advance. On real data, each would have produced a result I could have defended and published.",
        ],
      },
    ],
  },
];

export function getPost(slug: string): JournalPost | undefined {
  return JOURNAL_POSTS.find((post) => post.slug === slug);
}
